"""add school_applications and verification_tokens table

Revision ID: 8f70c12efe02
Revises: bd442a3256ab
Create Date: 2026-01-12 12:56:53.460073

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f70c12efe02"
down_revision: str | Sequence[str] | None = "bd442a3256ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("school_name", sa.String(length=200), nullable=False),
        sa.Column("year_established", sa.Integer(), nullable=False),
        sa.Column(
            "school_type",
            sa.Enum("PUBLIC", "PRIVATE", "MISSION", "UNIVERSITY", "VOCATIONAL", name="school_type"),
            nullable=False,
        ),
        sa.Column(
            "student_population",
            sa.Enum(
                "UNDER_100",
                "FROM_100_TO_300",
                "FROM_300_TO_500",
                "OVER_500",
                name="student_population",
            ),
            nullable=False,
        ),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("school_phone", sa.String(length=20), nullable=True),
        sa.Column("school_email", sa.String(length=255), nullable=True),
        sa.Column("principal_name", sa.String(length=200), nullable=False),
        sa.Column("principal_email", sa.String(length=255), nullable=False),
        sa.Column("principal_phone", sa.String(length=20), nullable=False),
        sa.Column("applicant_is_principal", sa.Boolean(), nullable=False),
        sa.Column("applicant_name", sa.String(length=200), nullable=True),
        sa.Column("applicant_email", sa.String(length=255), nullable=True),
        sa.Column("applicant_phone", sa.String(length=20), nullable=True),
        sa.Column("applicant_role", sa.String(length=100), nullable=True),
        sa.Column(
            "admin_choice", sa.Enum("APPLICANT", "PRINCIPAL", name="admin_choice"), nullable=True
        ),
        sa.Column("online_presence", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("reasons", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("other_reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AWAITING_APPLICANT_VERIFICATION",
                "AWAITING_PRINCIPAL_CONFIRMATION",
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                name="application_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applicant_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("principal_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_school_applications_applicant_email",
        "school_applications",
        ["applicant_email"],
        unique=False,
    )
    op.create_index(
        "ix_school_applications_principal_email",
        "school_applications",
        ["principal_email"],
        unique=False,
    )
    op.create_index(
        "ix_school_applications_school_city",
        "school_applications",
        ["school_name", "city"],
        unique=False,
    )
    op.create_index(
        "ix_school_applications_status", "school_applications", ["status"], unique=False
    )
    op.create_table(
        "verification_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum("APPLICANT_VERIFICATION", "PRINCIPAL_CONFIRMATION", name="token_type"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["school_applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index("ix_verification_tokens_token", "verification_tokens", ["token"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verification_tokens_token", table_name="verification_tokens")
    op.drop_table("verification_tokens")
    op.drop_index("ix_school_applications_status", table_name="school_applications")
    op.drop_index("ix_school_applications_school_city", table_name="school_applications")
    op.drop_index("ix_school_applications_principal_email", table_name="school_applications")
    op.drop_index("ix_school_applications_applicant_email", table_name="school_applications")
    op.drop_table("school_applications")
    # ### end Alembic commands ###
